### PR TITLE
Added multiply function

### LINKED ISSUE #5: Developing multiply function and its handler
On this step user can run a function multiply by pressing on appropriate button.
This function multiplies the user input by the previously set number.

Steps 

- [x] The new repo branch multiply was generated.

- [x] The core logic function was developed.

- [x] It was passed through a set of tests.

- [x] An appropriate handler was developed to use the function interactively.

- [x] PR was raised, reviewed by two assigned reviewers and the branch. was merged to the master branch.

### PR DESCRIPTION
**Pull request by fmkarakus**
Please review multiply function.
Closes #5

### CODE REVIEW

**Review by pavelbidenko2018 — APPROVED** [review]
OK - could not see something not good

**Review by LujiAnna — COMMENTED** [review]
Looks good

**Review by LujiAnna — APPROVED** [review]
I forgot to approve :)

**Review by gelilaa — APPROVED** [review]
very well done @fmkarakus 💯

**Pull request merged**
